// Seed dataset for prisma/seed.ts. Also the source for content that was
// deliberately kept static rather than modeled as a DB table (FAQ copy,
// and the landing page's decorative dashboard-preview mockup).
//
// Generated by scripts/generate-seed-data.ts — regenerate with
// `bun run scripts/generate-seed-data.ts` rather than hand-editing bulk
// content below. All dates are stored as offsets (daysAgo / daysOffset /
// daysInDays), resolved against Date.now() at prisma/seed.ts run time, so
// this dataset never goes stale. Team accounts (Alok/Vishal/Pardhiv/
// Purnendu/Ashish) are seeded separately, directly in prisma/seed.ts.

export type ClubCategory = "Technical" | "Cultural" | "Sports" | "Entrepreneurship" | "Literary" | "Social" | "Design";

export interface Club {
  id: string;
  slug: string;
  name: string;
  tagline: string;
  category: ClubCategory;
  members: number;
  active: boolean;
  hue: string;
  emoji: string;
  lastEvent: string;
  founded: string;
  description: string;
  banner: string;
  photo?: string;
}

function clubGradient(hue: string): string {
  return `linear-gradient(135deg, oklch(0.32 0.09 ${hue}) 0%, oklch(0.15 0.04 ${hue}) 100%)`;
}

export const clubs: Club[] = [
  { id: "c1", slug: "codechef", name: "CodeChef IITM BS", tagline: "Competitive programming, weekly contests.", category: "Technical", members: 13, active: true, hue: "122", emoji: "◉", lastEvent: "2 weeks ago", founded: "2021", description: "Weekly cook-offs, algorithm deep-dives, and interview prep circles. Home for anyone who thinks in edge cases.", banner: clubGradient("122"), photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-banners/codechef.jpg" },
  { id: "c2", slug: "paradox", name: "Paradox Debate Society", tagline: "Parliamentary debate, MUN prep, public speaking.", category: "Literary", members: 10, active: true, hue: "5", emoji: "❋", lastEvent: "3 weeks ago", founded: "2020", description: "British Parliamentary debate, Model UN prep, and public speaking workshops. Weekly practice rounds, traveling squad.", banner: clubGradient("5"), photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-banners/paradox.jpg" },
  { id: "c3", slug: "sarga", name: "Sarga Music Circle", tagline: "Fusion, jams, semester showcases.", category: "Cultural", members: 11, active: true, hue: "260", emoji: "♪", lastEvent: "3 weeks ago", founded: "2019", description: "Instrumentalists, vocalists, producers. Open jam every Friday, big fusion show every semester, open mic nights.", banner: clubGradient("260"), photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-banners/sarga.jpg" },
  { id: "c4", slug: "kalakriti", name: "Kalakriti Design Guild", tagline: "Product/UI design, illustration critique.", category: "Design", members: 13, active: true, hue: "85", emoji: "◐", lastEvent: "3 weeks ago", founded: "2022", description: "Portfolio reviews, Figma workshops, brand studies, illustration critique. Cross-pollination with product & marketing.", banner: clubGradient("85"), photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-banners/kalakriti.jpg" },
  { id: "c5", slug: "prakriti", name: "Prakriti Sustainability", tagline: "Campus greening, climate action, waste audits.", category: "Social", members: 8, active: true, hue: "155", emoji: "❦", lastEvent: "2 weeks ago", founded: "2021", description: "Campus greening campaigns, climate action drives, and waste audits. Zero-waste campaigns and climate literacy workshops for local schools.", banner: clubGradient("155"), photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-banners/prakriti.jpg" },
  { id: "c6", slug: "e-cell", name: "E-Cell IITM BS", tagline: "Founder circles, startup weekends, pitch practice.", category: "Entrepreneurship", members: 15, active: true, hue: "45", emoji: "◈", lastEvent: "10 days ago", founded: "2019", description: "Founder circles, mentor office hours, pitch practice, and the annual Ignite startup weekend. Alumni founder network.", banner: clubGradient("45"), photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-banners/e-cell.jpg" },
  { id: "c7", slug: "quill", name: "Quill Writers' Circle", tagline: "Prose, poetry, longform criticism, writing sprints.", category: "Literary", members: 9, active: false, hue: "320", emoji: "✦", lastEvent: "8 weeks ago", founded: "2022", description: "Monthly zine, workshop rounds, and reading nights. Fiction, poetry, essays, longform criticism, writing sprints, all welcome.", banner: clubGradient("320"), photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-banners/quill.jpg" },
  { id: "c8", slug: "arena", name: "Arena Chess Club", tagline: "Blitz, bullet, and team leagues, rating ladder.", category: "Sports", members: 10, active: true, hue: "0", emoji: "♞", lastEvent: "3 weeks ago", founded: "2020", description: "Weekly blitz and bullet nights, inter-college team leagues, opening prep clinics, and a running rating ladder. Beginners always welcome.", banner: clubGradient("0"), photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-banners/arena.jpg" },
];

export type EventStatus = "upcoming" | "live" | "past";
export interface Event {
  id: string;
  slug: string;
  title: string;
  clubSlug: string;
  club: string;
  date: string;
  isoDate: string;
  daysOffset: number;
  time: string;
  venue: string;
  status: EventStatus;
  going: number;
  capacity: number;
  cover: string;
  photo?: string;
  tags: string[];
  description: string;
  approval: "approved" | "pending" | "not-required" | "rejected";
}

export const events: Event[] = [
  { id: "e1", slug: "weekly-cook-off-47-codechef", title: "Weekly Cook-Off #47", clubSlug: "codechef", club: "CodeChef IITM BS", date: "Mon, Jul 6", isoDate: "2026-07-06", daysOffset: -35, time: "9:00 AM", venue: "Online · Discord", status: "past", going: 218, capacity: 300, cover: "linear-gradient(135deg,#d4ff3a 0%,#22d3ee 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/cook-off-42.png", tags: ["Contest","Online"], description: "Four problems, two hours, one leaderboard. Editorial released 10 minutes after end.", approval: "not-required" },
  { id: "e2", slug: "dsa-bootcamp-trees-graphs-codechef", title: "DSA Bootcamp: Trees & Graphs", clubSlug: "codechef", club: "CodeChef IITM BS", date: "Mon, Jul 20", isoDate: "2026-07-20", daysOffset: -21, time: "10:00 AM", venue: "Seminar Hall 2", status: "past", going: 85, capacity: 90, cover: "linear-gradient(135deg,#d4ff3a 0%,#22d3ee 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/hacktoberfest.jpg", tags: ["Workshop"], description: "From first principles to lazy propagation, with practice problems to close.", approval: "not-required" },
  { id: "e3", slug: "hack-a-sangam-24h-codechef", title: "Hack-a-Sangam 24h", clubSlug: "codechef", club: "CodeChef IITM BS", date: "Mon, Jul 27", isoDate: "2026-07-27", daysOffset: -14, time: "2:00 PM", venue: "CRC Auditorium", status: "past", going: 96, capacity: 100, cover: "linear-gradient(135deg,#d4ff3a 0%,#22d3ee 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/cook-off-42.png", tags: ["Hackathon"], description: "24-hour build sprint, mentors on rotation, demos judged live at the end.", approval: "not-required" },
  { id: "e4", slug: "weekly-cook-off-48-codechef", title: "Weekly Cook-Off #48", clubSlug: "codechef", club: "CodeChef IITM BS", date: "Wed, Aug 12", isoDate: "2026-08-12", daysOffset: 2, time: "5:00 PM", venue: "Online · Discord", status: "upcoming", going: 140, capacity: 300, cover: "linear-gradient(135deg,#d4ff3a 0%,#22d3ee 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/cook-off-42.png", tags: ["Contest","Online"], description: "Four problems, two hours, one leaderboard. Editorial released 10 minutes after end.", approval: "approved" },
  { id: "e5", slug: "placement-prep-system-design-crash-course-codechef", title: "Placement Prep: System Design Crash Course", clubSlug: "codechef", club: "CodeChef IITM BS", date: "Thu, Aug 20", isoDate: "2026-08-20", daysOffset: 10, time: "6:30 PM", venue: "Seminar Hall 1", status: "upcoming", going: 0, capacity: 100, cover: "linear-gradient(135deg,#d4ff3a 0%,#22d3ee 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/hacktoberfest.jpg", tags: ["Careers","Workshop"], description: "Load balancers to sharding, with two whiteboard case studies.", approval: "pending" },
  { id: "e6", slug: "bp-open-round-paradox", title: "BP Open Round", clubSlug: "paradox", club: "Paradox Debate Society", date: "Wed, Jul 1", isoDate: "2026-07-01", daysOffset: -40, time: "7:00 PM", venue: "Seminar Hall 3", status: "past", going: 42, capacity: 60, cover: "linear-gradient(135deg,#ff4d8f 0%,#a855f7 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/bp-open-round.png", tags: ["Debate"], description: "British Parliamentary format. Motions announced 15 minutes before each round.", approval: "not-required" },
  { id: "e7", slug: "novice-parliamentary-workshop-paradox", title: "Novice Parliamentary Workshop", clubSlug: "paradox", club: "Paradox Debate Society", date: "Thu, Jul 16", isoDate: "2026-07-16", daysOffset: -25, time: "9:00 PM", venue: "Seminar Hall 2", status: "past", going: 55, capacity: 60, cover: "linear-gradient(135deg,#ff4d8f 0%,#a855f7 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/cat-mun-conference.jpg", tags: ["Debate","Workshop"], description: "First-timer friendly. POI drills, case construction, and a mock round.", approval: "not-required" },
  { id: "e8", slug: "inter-iit-mun-selection-trials-paradox", title: "Inter-IIT MUN Selection Trials", clubSlug: "paradox", club: "Paradox Debate Society", date: "Thu, Jul 23", isoDate: "2026-07-23", daysOffset: -18, time: "9:00 AM", venue: "CRC Auditorium", status: "past", going: 40, capacity: 45, cover: "linear-gradient(135deg,#ff4d8f 0%,#a855f7 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/cat-mun-conference.jpg", tags: ["MUN"], description: "Position paper review and committee simulation to shortlist the travel delegation.", approval: "not-required" },
  { id: "e9", slug: "fusion-night-debate-exhibition-paradox", title: "Fusion Night Debate Exhibition", clubSlug: "paradox", club: "Paradox Debate Society", date: "Sun, Aug 16", isoDate: "2026-08-16", daysOffset: 6, time: "10:00 AM", venue: "Amphitheatre", status: "upcoming", going: 30, capacity: 80, cover: "linear-gradient(135deg,#ff4d8f 0%,#a855f7 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/bp-open-round.png", tags: ["Debate","Exhibition"], description: "An exhibition round pairing debate with Sarga's Fusion Night crowd — showcase format, audience judged.", approval: "approved" },
  { id: "e10", slug: "bp-open-round-ii-paradox", title: "BP Open Round II", clubSlug: "paradox", club: "Paradox Debate Society", date: "Tue, Aug 25", isoDate: "2026-08-25", daysOffset: 15, time: "2:00 PM", venue: "Seminar Hall 3", status: "upcoming", going: 0, capacity: 60, cover: "linear-gradient(135deg,#ff4d8f 0%,#a855f7 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/bp-open-round.png", tags: ["Debate"], description: "British Parliamentary format. Motions announced 15 minutes before each round.", approval: "pending" },
  { id: "e11", slug: "fusion-night-vi-sarga-live-sarga", title: "Fusion Night VI — Sarga Live", clubSlug: "sarga", club: "Sarga Music Circle", date: "Fri, Aug 14", isoDate: "2026-08-14", daysOffset: 4, time: "5:00 PM", venue: "Amphitheatre", status: "upcoming", going: 187, capacity: 250, cover: "linear-gradient(135deg,#7c3aed 0%,#ec4899 60%,#f97316 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/fusion-night-vi.png", tags: ["Music","Open"], description: "The flagship fusion showcase. Six acts, one hour of chaos, one hour of soul.", approval: "approved" },
  { id: "e12", slug: "open-mic-monsoon-edition-sarga", title: "Open Mic: Monsoon Edition", clubSlug: "sarga", club: "Sarga Music Circle", date: "Sat, Jul 11", isoDate: "2026-07-11", daysOffset: -30, time: "6:30 PM", venue: "OAT", status: "past", going: 120, capacity: 130, cover: "linear-gradient(135deg,#7c3aed 0%,#ec4899 60%,#f97316 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/sarga-open-jam.png", tags: ["Music","Open"], description: "Open mic slots, ten minutes each, sign up on the day.", approval: "not-required" },
  { id: "e13", slug: "acoustic-jam-session-sarga", title: "Acoustic Jam Session", clubSlug: "sarga", club: "Sarga Music Circle", date: "Tue, Jul 21", isoDate: "2026-07-21", daysOffset: -20, time: "7:00 PM", venue: "Seminar Hall 1", status: "past", going: 45, capacity: 50, cover: "linear-gradient(135deg,#7c3aed 0%,#ec4899 60%,#f97316 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/cat-music-studio.jpg", tags: ["Music"], description: "Stripped-down acoustic sets, string and wind instruments only.", approval: "not-required" },
  { id: "e14", slug: "semester-showcase-ragas-rhythms-sarga", title: "Semester Showcase: Ragas & Rhythms", clubSlug: "sarga", club: "Sarga Music Circle", date: "Thu, Jun 11", isoDate: "2026-06-11", daysOffset: -60, time: "9:00 PM", venue: "CRC Auditorium", status: "past", going: 300, capacity: 320, cover: "linear-gradient(135deg,#7c3aed 0%,#ec4899 60%,#f97316 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/cat-music-performance.jpg", tags: ["Music","Flagship"], description: "Semester-closing showcase, fourteen acts across genres.", approval: "not-required" },
  { id: "e15", slug: "battle-of-bands-auditions-sarga", title: "Battle of Bands Auditions", clubSlug: "sarga", club: "Sarga Music Circle", date: "Sat, Aug 22", isoDate: "2026-08-22", daysOffset: 12, time: "9:00 AM", venue: "OAT", status: "upcoming", going: 0, capacity: 60, cover: "linear-gradient(135deg,#7c3aed 0%,#ec4899 60%,#f97316 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/sarga-open-jam.png", tags: ["Music","Competition"], description: "Five-minute set auditions for a slot in this semester's Battle of Bands.", approval: "pending" },
  { id: "e16", slug: "portfolio-critique-circle-12-kalakriti", title: "Portfolio Critique Circle #12", clubSlug: "kalakriti", club: "Kalakriti Design Guild", date: "Sun, Jul 19", isoDate: "2026-07-19", daysOffset: -22, time: "10:00 AM", venue: "Seminar Hall 2", status: "past", going: 30, capacity: 35, cover: "linear-gradient(135deg,#eab308 0%,#84cc16 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/portfolio-crit.png", tags: ["Design"], description: "Bring three screens or one case study. Ten-minute slots, brutally honest, brutally kind.", approval: "not-required" },
  { id: "e17", slug: "ui-ux-bootcamp-weekend-kalakriti", title: "UI/UX Bootcamp Weekend", clubSlug: "kalakriti", club: "Kalakriti Design Guild", date: "Mon, Jul 6", isoDate: "2026-07-06", daysOffset: -35, time: "2:00 PM", venue: "Seminar Hall 1", status: "past", going: 65, capacity: 70, cover: "linear-gradient(135deg,#eab308 0%,#84cc16 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/cat-electronics-workshop.jpg", tags: ["Design","Workshop"], description: "Two-day intensive: heuristics, wireframes, and a live redesign critique.", approval: "not-required" },
  { id: "e18", slug: "design-fest-prakriti-x-kalakriti-collab-showcase-kalakriti", title: "Design Fest: Prakriti x Kalakriti Collab Showcase", clubSlug: "kalakriti", club: "Kalakriti Design Guild", date: "Fri, Jun 26", isoDate: "2026-06-26", daysOffset: -45, time: "5:00 PM", venue: "Amphitheatre", status: "past", going: 150, capacity: 160, cover: "linear-gradient(135deg,#eab308 0%,#84cc16 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/portfolio-crit.png", tags: ["Design","Exhibition"], description: "Cross-club exhibit pairing sustainability storytelling with design craft.", approval: "not-required" },
  { id: "e19", slug: "illustration-sprint-campus-stories-kalakriti", title: "Illustration Sprint: Campus Stories", clubSlug: "kalakriti", club: "Kalakriti Design Guild", date: "Tue, Aug 18", isoDate: "2026-08-18", daysOffset: 8, time: "6:30 PM", venue: "Seminar Hall 3", status: "upcoming", going: 25, capacity: 50, cover: "linear-gradient(135deg,#eab308 0%,#84cc16 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/cat-robotics-team.jpg", tags: ["Design","Sprint"], description: "A day-long illustration sprint documenting campus life, exhibited the following week.", approval: "approved" },
  { id: "e20", slug: "campus-waste-audit-drive-prakriti", title: "Campus Waste Audit Drive", clubSlug: "prakriti", club: "Prakriti Sustainability", date: "Thu, Jul 16", isoDate: "2026-07-16", daysOffset: -25, time: "7:00 PM", venue: "Meet at Main Gate", status: "past", going: 40, capacity: 45, cover: "linear-gradient(135deg,#22c55e 0%,#0891b2 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/cat-football-match.jpg", tags: ["Volunteer"], description: "Full-campus waste segregation audit, findings compiled into a report for facilities.", approval: "not-required" },
  { id: "e21", slug: "climate-action-panel-prakriti", title: "Climate Action Panel", clubSlug: "prakriti", club: "Prakriti Sustainability", date: "Sun, Jul 26", isoDate: "2026-07-26", daysOffset: -15, time: "9:00 PM", venue: "Seminar Hall 1", status: "past", going: 70, capacity: 75, cover: "linear-gradient(135deg,#22c55e 0%,#0891b2 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/cat-mun-conference.jpg", tags: ["Panel"], description: "Panel discussion with campus sustainability office and two alumni founders.", approval: "not-required" },
  { id: "e22", slug: "tree-plantation-weekend-prakriti", title: "Tree Plantation Weekend", clubSlug: "prakriti", club: "Prakriti Sustainability", date: "Wed, Aug 19", isoDate: "2026-08-19", daysOffset: 9, time: "9:00 AM", venue: "Campus Grounds", status: "upcoming", going: 55, capacity: 100, cover: "linear-gradient(135deg,#22c55e 0%,#0891b2 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/climate-teach-in.png", tags: ["Volunteer","Campaign"], description: "Weekend plantation drive across the campus grounds, saplings and tools provided.", approval: "approved" },
  { id: "e23", slug: "sustainability-fair-prakriti", title: "Sustainability Fair", clubSlug: "prakriti", club: "Prakriti Sustainability", date: "Sun, Aug 30", isoDate: "2026-08-30", daysOffset: 20, time: "10:00 AM", venue: "OAT", status: "upcoming", going: 0, capacity: 150, cover: "linear-gradient(135deg,#22c55e 0%,#0891b2 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/cat-football-match.jpg", tags: ["Fair"], description: "Stalls, workshops, and a repair cafe — campus-wide sustainability showcase.", approval: "pending" },
  { id: "e24", slug: "founder-circle-fundraising-101-e-cell", title: "Founder Circle: Fundraising 101", clubSlug: "e-cell", club: "E-Cell IITM BS", date: "Mon, Jul 13", isoDate: "2026-07-13", daysOffset: -28, time: "2:00 PM", venue: "Seminar Hall 2", status: "past", going: 60, capacity: 65, cover: "linear-gradient(135deg,#f97316 0%,#eab308 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/cat-mun-conference.jpg", tags: ["Founders"], description: "Alumni founder walks through a real pitch deck and term sheet, Q&A after.", approval: "not-required" },
  { id: "e25", slug: "startup-weekend-e-cell", title: "Startup Weekend", clubSlug: "e-cell", club: "E-Cell IITM BS", date: "Sun, Jun 21", isoDate: "2026-06-21", daysOffset: -50, time: "5:00 PM", venue: "CRC Auditorium", status: "past", going: 210, capacity: 220, cover: "linear-gradient(135deg,#f97316 0%,#eab308 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/ignite-2026.png", tags: ["Flagship"], description: "54-hour build-a-startup weekend, culminating in pitches to a VC judging panel.", approval: "not-required" },
  { id: "e26", slug: "pitch-practice-fridays-9-e-cell", title: "Pitch Practice Fridays #9", clubSlug: "e-cell", club: "E-Cell IITM BS", date: "Fri, Jul 31", isoDate: "2026-07-31", daysOffset: -10, time: "6:30 PM", venue: "Online · Zoom", status: "past", going: 35, capacity: 40, cover: "linear-gradient(135deg,#f97316 0%,#eab308 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/hacktoberfest.jpg", tags: ["Practice"], description: "Rapid-fire two-minute pitch practice with peer feedback.", approval: "not-required" },
  { id: "e27", slug: "ignite-2026-startup-weekend-e-cell", title: "Ignite 2026 — Startup Weekend", clubSlug: "e-cell", club: "E-Cell IITM BS", date: "Mon, Aug 17", isoDate: "2026-08-17", daysOffset: 7, time: "7:00 PM", venue: "IITM Research Park", status: "upcoming", going: 96, capacity: 300, cover: "linear-gradient(135deg,#f97316 0%,#eab308 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/ignite-2026.png", tags: ["Flagship","All-day"], description: "The club's flagship startup weekend — sponsor booths, mentor circuit, and a live pitch finale.", approval: "approved" },
  { id: "e28", slug: "founder-ama-series-a-lessons-e-cell", title: "Founder AMA: Series A Lessons", clubSlug: "e-cell", club: "E-Cell IITM BS", date: "Fri, Sep 4", isoDate: "2026-09-04", daysOffset: 25, time: "9:00 PM", venue: "Seminar Hall 1", status: "upcoming", going: 0, capacity: 80, cover: "linear-gradient(135deg,#f97316 0%,#eab308 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/cat-mun-conference.jpg", tags: ["Founders","AMA"], description: "An alumna founder on what actually broke during her Series A, ask-anything format.", approval: "pending" },
  { id: "e29", slug: "poetry-slam-monsoon-verses-quill", title: "Poetry Slam: Monsoon Verses", clubSlug: "quill", club: "Quill Writers' Circle", date: "Mon, Jun 1", isoDate: "2026-06-01", daysOffset: -70, time: "9:00 AM", venue: "Amphitheatre", status: "past", going: 50, capacity: 55, cover: "linear-gradient(135deg,#ec4899 0%,#a855f7 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/cat-mun-conference.jpg", tags: ["Poetry"], description: "Open poetry slam, five-minute slots, judged by audience applause meter.", approval: "not-required" },
  { id: "e30", slug: "writing-sprint-saturday-quill", title: "Writing Sprint Saturday", clubSlug: "quill", club: "Quill Writers' Circle", date: "Tue, Jun 16", isoDate: "2026-06-16", daysOffset: -55, time: "10:00 AM", venue: "Seminar Hall 3", status: "past", going: 22, capacity: 25, cover: "linear-gradient(135deg,#ec4899 0%,#a855f7 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/hacktoberfest.jpg", tags: ["Sprint"], description: "Silent-writing sprints in 25-minute blocks, share-out at the end.", approval: "not-required" },
  { id: "e31", slug: "longform-critique-circle-7-quill", title: "Longform Critique Circle #7", clubSlug: "quill", club: "Quill Writers' Circle", date: "Mon, Sep 14", isoDate: "2026-09-14", daysOffset: 35, time: "2:00 PM", venue: "Seminar Hall 2", status: "upcoming", going: 18, capacity: 30, cover: "linear-gradient(135deg,#ec4899 0%,#a855f7 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/cat-electronics-workshop.jpg", tags: ["Critique"], description: "Essay-length pieces workshopped in small groups, written feedback required in advance.", approval: "approved" },
  { id: "e32", slug: "campus-anthology-launch-quill", title: "Campus Anthology Launch", clubSlug: "quill", club: "Quill Writers' Circle", date: "Thu, Sep 24", isoDate: "2026-09-24", daysOffset: 45, time: "5:00 PM", venue: "OAT", status: "upcoming", going: 0, capacity: 80, cover: "linear-gradient(135deg,#ec4899 0%,#a855f7 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/cat-mun-conference.jpg", tags: ["Launch"], description: "Launch reading for this year's campus anthology, contributors read excerpts.", approval: "pending" },
  { id: "e33", slug: "blitz-ladder-round-4-arena", title: "Blitz Ladder Round 4", clubSlug: "arena", club: "Arena Chess Club", date: "Wed, Jul 8", isoDate: "2026-07-08", daysOffset: -33, time: "6:30 PM", venue: "Seminar Hall 1", status: "past", going: 32, capacity: 35, cover: "linear-gradient(135deg,#ef4444 0%,#7c3aed 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/chess-blitz-x.png", tags: ["Blitz","Ladder"], description: "Round 4 of the ongoing blitz ladder, Swiss pairing, five-minute clocks.", approval: "not-required" },
  { id: "e34", slug: "team-league-semifinals-arena", title: "Team League: Semifinals", clubSlug: "arena", club: "Arena Chess Club", date: "Tue, Jul 21", isoDate: "2026-07-21", daysOffset: -20, time: "7:00 PM", venue: "Seminar Hall 3", status: "past", going: 28, capacity: 30, cover: "linear-gradient(135deg,#ef4444 0%,#7c3aed 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/cat-chess-tournament.jpg", tags: ["League"], description: "Board-by-board semifinal match between the season's top two teams.", approval: "not-required" },
  { id: "e35", slug: "bullet-chess-night-arena", title: "Bullet Chess Night", clubSlug: "arena", club: "Arena Chess Club", date: "Sat, Aug 15", isoDate: "2026-08-15", daysOffset: 5, time: "9:00 PM", venue: "Seminar Hall 1", status: "upcoming", going: 40, capacity: 60, cover: "linear-gradient(135deg,#ef4444 0%,#7c3aed 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/chess-blitz-x.png", tags: ["Bullet"], description: "One-minute bullet chess, knockout bracket, arbiter on hand for disputes.", approval: "approved" },
  { id: "e36", slug: "rating-ladder-round-5-arena", title: "Rating Ladder Round 5", clubSlug: "arena", club: "Arena Chess Club", date: "Fri, Aug 28", isoDate: "2026-08-28", daysOffset: 18, time: "9:00 AM", venue: "Seminar Hall 3", status: "upcoming", going: 0, capacity: 50, cover: "linear-gradient(135deg,#ef4444 0%,#7c3aed 100%)", photo: "https://os40qg3iuevjlpga.public.blob.vercel-storage.com/club-events/cat-chess-tournament.jpg", tags: ["Ladder"], description: "Round 5 of the ongoing rating ladder, Swiss pairing.", approval: "pending" },
];

export interface EventAttendee {
  eventSlug: string;
  memberId: string;
  checkedIn: boolean;
  registeredDaysAgo: number;
}
export const eventAttendees: EventAttendee[] = [
  { eventSlug: "weekly-cook-off-47-codechef", memberId: "m1", checkedIn: true, registeredDaysAgo: 36 },
  { eventSlug: "weekly-cook-off-47-codechef", memberId: "m19", checkedIn: true, registeredDaysAgo: 37 },
  { eventSlug: "weekly-cook-off-47-codechef", memberId: "m5", checkedIn: true, registeredDaysAgo: 38 },
  { eventSlug: "weekly-cook-off-47-codechef", memberId: "m24", checkedIn: true, registeredDaysAgo: 39 },
  { eventSlug: "weekly-cook-off-47-codechef", memberId: "m7", checkedIn: true, registeredDaysAgo: 40 },
  { eventSlug: "weekly-cook-off-47-codechef", memberId: "m27", checkedIn: true, registeredDaysAgo: 41 },
  { eventSlug: "dsa-bootcamp-trees-graphs-codechef", memberId: "m1", checkedIn: true, registeredDaysAgo: 22 },
  { eventSlug: "dsa-bootcamp-trees-graphs-codechef", memberId: "m19", checkedIn: true, registeredDaysAgo: 23 },
  { eventSlug: "dsa-bootcamp-trees-graphs-codechef", memberId: "m5", checkedIn: true, registeredDaysAgo: 24 },
  { eventSlug: "dsa-bootcamp-trees-graphs-codechef", memberId: "m24", checkedIn: true, registeredDaysAgo: 25 },
  { eventSlug: "dsa-bootcamp-trees-graphs-codechef", memberId: "m7", checkedIn: true, registeredDaysAgo: 26 },
  { eventSlug: "dsa-bootcamp-trees-graphs-codechef", memberId: "m27", checkedIn: true, registeredDaysAgo: 27 },
  { eventSlug: "hack-a-sangam-24h-codechef", memberId: "m1", checkedIn: true, registeredDaysAgo: 15 },
  { eventSlug: "hack-a-sangam-24h-codechef", memberId: "m19", checkedIn: true, registeredDaysAgo: 16 },
  { eventSlug: "hack-a-sangam-24h-codechef", memberId: "m5", checkedIn: true, registeredDaysAgo: 17 },
  { eventSlug: "hack-a-sangam-24h-codechef", memberId: "m24", checkedIn: true, registeredDaysAgo: 18 },
  { eventSlug: "hack-a-sangam-24h-codechef", memberId: "m7", checkedIn: true, registeredDaysAgo: 19 },
  { eventSlug: "hack-a-sangam-24h-codechef", memberId: "m27", checkedIn: true, registeredDaysAgo: 20 },
  { eventSlug: "weekly-cook-off-48-codechef", memberId: "m1", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "weekly-cook-off-48-codechef", memberId: "m19", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "weekly-cook-off-48-codechef", memberId: "m5", checkedIn: false, registeredDaysAgo: 2 },
  { eventSlug: "weekly-cook-off-48-codechef", memberId: "m24", checkedIn: false, registeredDaysAgo: 3 },
  { eventSlug: "weekly-cook-off-48-codechef", memberId: "m7", checkedIn: false, registeredDaysAgo: 4 },
  { eventSlug: "weekly-cook-off-48-codechef", memberId: "m27", checkedIn: false, registeredDaysAgo: 5 },
  { eventSlug: "placement-prep-system-design-crash-course-codechef", memberId: "m1", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "placement-prep-system-design-crash-course-codechef", memberId: "m19", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "placement-prep-system-design-crash-course-codechef", memberId: "m5", checkedIn: false, registeredDaysAgo: 2 },
  { eventSlug: "placement-prep-system-design-crash-course-codechef", memberId: "m24", checkedIn: false, registeredDaysAgo: 3 },
  { eventSlug: "placement-prep-system-design-crash-course-codechef", memberId: "m7", checkedIn: false, registeredDaysAgo: 4 },
  { eventSlug: "placement-prep-system-design-crash-course-codechef", memberId: "m27", checkedIn: false, registeredDaysAgo: 5 },
  { eventSlug: "bp-open-round-paradox", memberId: "m2", checkedIn: true, registeredDaysAgo: 41 },
  { eventSlug: "bp-open-round-paradox", memberId: "m31", checkedIn: true, registeredDaysAgo: 42 },
  { eventSlug: "bp-open-round-paradox", memberId: "m23", checkedIn: true, registeredDaysAgo: 43 },
  { eventSlug: "bp-open-round-paradox", memberId: "m6", checkedIn: true, registeredDaysAgo: 44 },
  { eventSlug: "bp-open-round-paradox", memberId: "m33", checkedIn: true, registeredDaysAgo: 45 },
  { eventSlug: "bp-open-round-paradox", memberId: "m25", checkedIn: true, registeredDaysAgo: 46 },
  { eventSlug: "novice-parliamentary-workshop-paradox", memberId: "m2", checkedIn: true, registeredDaysAgo: 26 },
  { eventSlug: "novice-parliamentary-workshop-paradox", memberId: "m31", checkedIn: true, registeredDaysAgo: 27 },
  { eventSlug: "novice-parliamentary-workshop-paradox", memberId: "m23", checkedIn: true, registeredDaysAgo: 28 },
  { eventSlug: "novice-parliamentary-workshop-paradox", memberId: "m6", checkedIn: true, registeredDaysAgo: 29 },
  { eventSlug: "novice-parliamentary-workshop-paradox", memberId: "m33", checkedIn: true, registeredDaysAgo: 30 },
  { eventSlug: "novice-parliamentary-workshop-paradox", memberId: "m25", checkedIn: true, registeredDaysAgo: 31 },
  { eventSlug: "inter-iit-mun-selection-trials-paradox", memberId: "m2", checkedIn: true, registeredDaysAgo: 19 },
  { eventSlug: "inter-iit-mun-selection-trials-paradox", memberId: "m31", checkedIn: true, registeredDaysAgo: 20 },
  { eventSlug: "inter-iit-mun-selection-trials-paradox", memberId: "m23", checkedIn: true, registeredDaysAgo: 21 },
  { eventSlug: "inter-iit-mun-selection-trials-paradox", memberId: "m6", checkedIn: true, registeredDaysAgo: 22 },
  { eventSlug: "inter-iit-mun-selection-trials-paradox", memberId: "m33", checkedIn: true, registeredDaysAgo: 23 },
  { eventSlug: "inter-iit-mun-selection-trials-paradox", memberId: "m25", checkedIn: true, registeredDaysAgo: 24 },
  { eventSlug: "fusion-night-debate-exhibition-paradox", memberId: "m2", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "fusion-night-debate-exhibition-paradox", memberId: "m31", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "fusion-night-debate-exhibition-paradox", memberId: "m23", checkedIn: false, registeredDaysAgo: 2 },
  { eventSlug: "fusion-night-debate-exhibition-paradox", memberId: "m6", checkedIn: false, registeredDaysAgo: 3 },
  { eventSlug: "fusion-night-debate-exhibition-paradox", memberId: "m33", checkedIn: false, registeredDaysAgo: 4 },
  { eventSlug: "fusion-night-debate-exhibition-paradox", memberId: "m25", checkedIn: false, registeredDaysAgo: 5 },
  { eventSlug: "bp-open-round-ii-paradox", memberId: "m2", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "bp-open-round-ii-paradox", memberId: "m31", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "bp-open-round-ii-paradox", memberId: "m23", checkedIn: false, registeredDaysAgo: 2 },
  { eventSlug: "bp-open-round-ii-paradox", memberId: "m6", checkedIn: false, registeredDaysAgo: 3 },
  { eventSlug: "bp-open-round-ii-paradox", memberId: "m33", checkedIn: false, registeredDaysAgo: 4 },
  { eventSlug: "bp-open-round-ii-paradox", memberId: "m25", checkedIn: false, registeredDaysAgo: 5 },
  { eventSlug: "fusion-night-vi-sarga-live-sarga", memberId: "m3", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "fusion-night-vi-sarga-live-sarga", memberId: "m26", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "fusion-night-vi-sarga-live-sarga", memberId: "m13", checkedIn: false, registeredDaysAgo: 2 },
  { eventSlug: "fusion-night-vi-sarga-live-sarga", memberId: "m37", checkedIn: false, registeredDaysAgo: 3 },
  { eventSlug: "fusion-night-vi-sarga-live-sarga", memberId: "m21", checkedIn: false, registeredDaysAgo: 4 },
  { eventSlug: "fusion-night-vi-sarga-live-sarga", memberId: "m9", checkedIn: false, registeredDaysAgo: 5 },
  { eventSlug: "open-mic-monsoon-edition-sarga", memberId: "m3", checkedIn: true, registeredDaysAgo: 31 },
  { eventSlug: "open-mic-monsoon-edition-sarga", memberId: "m26", checkedIn: true, registeredDaysAgo: 32 },
  { eventSlug: "open-mic-monsoon-edition-sarga", memberId: "m13", checkedIn: true, registeredDaysAgo: 33 },
  { eventSlug: "open-mic-monsoon-edition-sarga", memberId: "m37", checkedIn: true, registeredDaysAgo: 34 },
  { eventSlug: "open-mic-monsoon-edition-sarga", memberId: "m21", checkedIn: true, registeredDaysAgo: 35 },
  { eventSlug: "open-mic-monsoon-edition-sarga", memberId: "m9", checkedIn: true, registeredDaysAgo: 36 },
  { eventSlug: "acoustic-jam-session-sarga", memberId: "m3", checkedIn: true, registeredDaysAgo: 21 },
  { eventSlug: "acoustic-jam-session-sarga", memberId: "m26", checkedIn: true, registeredDaysAgo: 22 },
  { eventSlug: "acoustic-jam-session-sarga", memberId: "m13", checkedIn: true, registeredDaysAgo: 23 },
  { eventSlug: "acoustic-jam-session-sarga", memberId: "m37", checkedIn: true, registeredDaysAgo: 24 },
  { eventSlug: "acoustic-jam-session-sarga", memberId: "m21", checkedIn: true, registeredDaysAgo: 25 },
  { eventSlug: "acoustic-jam-session-sarga", memberId: "m9", checkedIn: true, registeredDaysAgo: 26 },
  { eventSlug: "semester-showcase-ragas-rhythms-sarga", memberId: "m3", checkedIn: true, registeredDaysAgo: 61 },
  { eventSlug: "semester-showcase-ragas-rhythms-sarga", memberId: "m26", checkedIn: true, registeredDaysAgo: 62 },
  { eventSlug: "semester-showcase-ragas-rhythms-sarga", memberId: "m13", checkedIn: true, registeredDaysAgo: 63 },
  { eventSlug: "semester-showcase-ragas-rhythms-sarga", memberId: "m37", checkedIn: true, registeredDaysAgo: 64 },
  { eventSlug: "semester-showcase-ragas-rhythms-sarga", memberId: "m21", checkedIn: true, registeredDaysAgo: 65 },
  { eventSlug: "semester-showcase-ragas-rhythms-sarga", memberId: "m9", checkedIn: true, registeredDaysAgo: 66 },
  { eventSlug: "battle-of-bands-auditions-sarga", memberId: "m3", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "battle-of-bands-auditions-sarga", memberId: "m26", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "battle-of-bands-auditions-sarga", memberId: "m13", checkedIn: false, registeredDaysAgo: 2 },
  { eventSlug: "battle-of-bands-auditions-sarga", memberId: "m37", checkedIn: false, registeredDaysAgo: 3 },
  { eventSlug: "battle-of-bands-auditions-sarga", memberId: "m21", checkedIn: false, registeredDaysAgo: 4 },
  { eventSlug: "battle-of-bands-auditions-sarga", memberId: "m9", checkedIn: false, registeredDaysAgo: 5 },
  { eventSlug: "portfolio-critique-circle-12-kalakriti", memberId: "m4", checkedIn: true, registeredDaysAgo: 23 },
  { eventSlug: "portfolio-critique-circle-12-kalakriti", memberId: "m25", checkedIn: true, registeredDaysAgo: 24 },
  { eventSlug: "portfolio-critique-circle-12-kalakriti", memberId: "m8", checkedIn: true, registeredDaysAgo: 25 },
  { eventSlug: "portfolio-critique-circle-12-kalakriti", memberId: "m27", checkedIn: true, registeredDaysAgo: 26 },
  { eventSlug: "portfolio-critique-circle-12-kalakriti", memberId: "m9", checkedIn: true, registeredDaysAgo: 27 },
  { eventSlug: "portfolio-critique-circle-12-kalakriti", memberId: "m30", checkedIn: true, registeredDaysAgo: 28 },
  { eventSlug: "ui-ux-bootcamp-weekend-kalakriti", memberId: "m4", checkedIn: true, registeredDaysAgo: 36 },
  { eventSlug: "ui-ux-bootcamp-weekend-kalakriti", memberId: "m25", checkedIn: true, registeredDaysAgo: 37 },
  { eventSlug: "ui-ux-bootcamp-weekend-kalakriti", memberId: "m8", checkedIn: true, registeredDaysAgo: 38 },
  { eventSlug: "ui-ux-bootcamp-weekend-kalakriti", memberId: "m27", checkedIn: true, registeredDaysAgo: 39 },
  { eventSlug: "ui-ux-bootcamp-weekend-kalakriti", memberId: "m9", checkedIn: true, registeredDaysAgo: 40 },
  { eventSlug: "ui-ux-bootcamp-weekend-kalakriti", memberId: "m30", checkedIn: true, registeredDaysAgo: 41 },
  { eventSlug: "design-fest-prakriti-x-kalakriti-collab-showcase-kalakriti", memberId: "m4", checkedIn: true, registeredDaysAgo: 46 },
  { eventSlug: "design-fest-prakriti-x-kalakriti-collab-showcase-kalakriti", memberId: "m25", checkedIn: true, registeredDaysAgo: 47 },
  { eventSlug: "design-fest-prakriti-x-kalakriti-collab-showcase-kalakriti", memberId: "m8", checkedIn: true, registeredDaysAgo: 48 },
  { eventSlug: "design-fest-prakriti-x-kalakriti-collab-showcase-kalakriti", memberId: "m27", checkedIn: true, registeredDaysAgo: 49 },
  { eventSlug: "design-fest-prakriti-x-kalakriti-collab-showcase-kalakriti", memberId: "m9", checkedIn: true, registeredDaysAgo: 50 },
  { eventSlug: "design-fest-prakriti-x-kalakriti-collab-showcase-kalakriti", memberId: "m30", checkedIn: true, registeredDaysAgo: 51 },
  { eventSlug: "illustration-sprint-campus-stories-kalakriti", memberId: "m4", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "illustration-sprint-campus-stories-kalakriti", memberId: "m25", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "illustration-sprint-campus-stories-kalakriti", memberId: "m8", checkedIn: false, registeredDaysAgo: 2 },
  { eventSlug: "illustration-sprint-campus-stories-kalakriti", memberId: "m27", checkedIn: false, registeredDaysAgo: 3 },
  { eventSlug: "illustration-sprint-campus-stories-kalakriti", memberId: "m9", checkedIn: false, registeredDaysAgo: 4 },
  { eventSlug: "illustration-sprint-campus-stories-kalakriti", memberId: "m30", checkedIn: false, registeredDaysAgo: 5 },
  { eventSlug: "campus-waste-audit-drive-prakriti", memberId: "m4", checkedIn: true, registeredDaysAgo: 26 },
  { eventSlug: "campus-waste-audit-drive-prakriti", memberId: "m36", checkedIn: true, registeredDaysAgo: 27 },
  { eventSlug: "campus-waste-audit-drive-prakriti", memberId: "m31", checkedIn: true, registeredDaysAgo: 28 },
  { eventSlug: "campus-waste-audit-drive-prakriti", memberId: "m28", checkedIn: true, registeredDaysAgo: 29 },
  { eventSlug: "campus-waste-audit-drive-prakriti", memberId: "m23", checkedIn: true, registeredDaysAgo: 30 },
  { eventSlug: "campus-waste-audit-drive-prakriti", memberId: "m20", checkedIn: true, registeredDaysAgo: 31 },
  { eventSlug: "climate-action-panel-prakriti", memberId: "m4", checkedIn: true, registeredDaysAgo: 16 },
  { eventSlug: "climate-action-panel-prakriti", memberId: "m36", checkedIn: true, registeredDaysAgo: 17 },
  { eventSlug: "climate-action-panel-prakriti", memberId: "m31", checkedIn: true, registeredDaysAgo: 18 },
  { eventSlug: "climate-action-panel-prakriti", memberId: "m28", checkedIn: true, registeredDaysAgo: 19 },
  { eventSlug: "climate-action-panel-prakriti", memberId: "m23", checkedIn: true, registeredDaysAgo: 20 },
  { eventSlug: "climate-action-panel-prakriti", memberId: "m20", checkedIn: true, registeredDaysAgo: 21 },
  { eventSlug: "tree-plantation-weekend-prakriti", memberId: "m4", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "tree-plantation-weekend-prakriti", memberId: "m36", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "tree-plantation-weekend-prakriti", memberId: "m31", checkedIn: false, registeredDaysAgo: 2 },
  { eventSlug: "tree-plantation-weekend-prakriti", memberId: "m28", checkedIn: false, registeredDaysAgo: 3 },
  { eventSlug: "tree-plantation-weekend-prakriti", memberId: "m23", checkedIn: false, registeredDaysAgo: 4 },
  { eventSlug: "tree-plantation-weekend-prakriti", memberId: "m20", checkedIn: false, registeredDaysAgo: 5 },
  { eventSlug: "sustainability-fair-prakriti", memberId: "m4", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "sustainability-fair-prakriti", memberId: "m36", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "sustainability-fair-prakriti", memberId: "m31", checkedIn: false, registeredDaysAgo: 2 },
  { eventSlug: "sustainability-fair-prakriti", memberId: "m28", checkedIn: false, registeredDaysAgo: 3 },
  { eventSlug: "sustainability-fair-prakriti", memberId: "m23", checkedIn: false, registeredDaysAgo: 4 },
  { eventSlug: "sustainability-fair-prakriti", memberId: "m20", checkedIn: false, registeredDaysAgo: 5 },
  { eventSlug: "founder-circle-fundraising-101-e-cell", memberId: "m1", checkedIn: true, registeredDaysAgo: 29 },
  { eventSlug: "founder-circle-fundraising-101-e-cell", memberId: "m19", checkedIn: true, registeredDaysAgo: 30 },
  { eventSlug: "founder-circle-fundraising-101-e-cell", memberId: "m34", checkedIn: true, registeredDaysAgo: 31 },
  { eventSlug: "founder-circle-fundraising-101-e-cell", memberId: "m14", checkedIn: true, registeredDaysAgo: 32 },
  { eventSlug: "founder-circle-fundraising-101-e-cell", memberId: "m27", checkedIn: true, registeredDaysAgo: 33 },
  { eventSlug: "founder-circle-fundraising-101-e-cell", memberId: "m7", checkedIn: true, registeredDaysAgo: 34 },
  { eventSlug: "startup-weekend-e-cell", memberId: "m1", checkedIn: true, registeredDaysAgo: 51 },
  { eventSlug: "startup-weekend-e-cell", memberId: "m19", checkedIn: true, registeredDaysAgo: 52 },
  { eventSlug: "startup-weekend-e-cell", memberId: "m34", checkedIn: true, registeredDaysAgo: 53 },
  { eventSlug: "startup-weekend-e-cell", memberId: "m14", checkedIn: true, registeredDaysAgo: 54 },
  { eventSlug: "startup-weekend-e-cell", memberId: "m27", checkedIn: true, registeredDaysAgo: 55 },
  { eventSlug: "startup-weekend-e-cell", memberId: "m7", checkedIn: true, registeredDaysAgo: 56 },
  { eventSlug: "pitch-practice-fridays-9-e-cell", memberId: "m1", checkedIn: true, registeredDaysAgo: 11 },
  { eventSlug: "pitch-practice-fridays-9-e-cell", memberId: "m19", checkedIn: true, registeredDaysAgo: 12 },
  { eventSlug: "pitch-practice-fridays-9-e-cell", memberId: "m34", checkedIn: true, registeredDaysAgo: 13 },
  { eventSlug: "pitch-practice-fridays-9-e-cell", memberId: "m14", checkedIn: true, registeredDaysAgo: 14 },
  { eventSlug: "pitch-practice-fridays-9-e-cell", memberId: "m27", checkedIn: true, registeredDaysAgo: 15 },
  { eventSlug: "pitch-practice-fridays-9-e-cell", memberId: "m7", checkedIn: true, registeredDaysAgo: 16 },
  { eventSlug: "ignite-2026-startup-weekend-e-cell", memberId: "m1", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "ignite-2026-startup-weekend-e-cell", memberId: "m19", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "ignite-2026-startup-weekend-e-cell", memberId: "m34", checkedIn: false, registeredDaysAgo: 2 },
  { eventSlug: "ignite-2026-startup-weekend-e-cell", memberId: "m14", checkedIn: false, registeredDaysAgo: 3 },
  { eventSlug: "ignite-2026-startup-weekend-e-cell", memberId: "m27", checkedIn: false, registeredDaysAgo: 4 },
  { eventSlug: "ignite-2026-startup-weekend-e-cell", memberId: "m7", checkedIn: false, registeredDaysAgo: 5 },
  { eventSlug: "founder-ama-series-a-lessons-e-cell", memberId: "m1", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "founder-ama-series-a-lessons-e-cell", memberId: "m19", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "founder-ama-series-a-lessons-e-cell", memberId: "m34", checkedIn: false, registeredDaysAgo: 2 },
  { eventSlug: "founder-ama-series-a-lessons-e-cell", memberId: "m14", checkedIn: false, registeredDaysAgo: 3 },
  { eventSlug: "founder-ama-series-a-lessons-e-cell", memberId: "m27", checkedIn: false, registeredDaysAgo: 4 },
  { eventSlug: "founder-ama-series-a-lessons-e-cell", memberId: "m7", checkedIn: false, registeredDaysAgo: 5 },
  { eventSlug: "poetry-slam-monsoon-verses-quill", memberId: "m2", checkedIn: true, registeredDaysAgo: 71 },
  { eventSlug: "poetry-slam-monsoon-verses-quill", memberId: "m33", checkedIn: true, registeredDaysAgo: 72 },
  { eventSlug: "poetry-slam-monsoon-verses-quill", memberId: "m25", checkedIn: true, registeredDaysAgo: 73 },
  { eventSlug: "poetry-slam-monsoon-verses-quill", memberId: "m19", checkedIn: true, registeredDaysAgo: 74 },
  { eventSlug: "poetry-slam-monsoon-verses-quill", memberId: "m6", checkedIn: true, registeredDaysAgo: 75 },
  { eventSlug: "poetry-slam-monsoon-verses-quill", memberId: "m38", checkedIn: true, registeredDaysAgo: 76 },
  { eventSlug: "writing-sprint-saturday-quill", memberId: "m2", checkedIn: true, registeredDaysAgo: 56 },
  { eventSlug: "writing-sprint-saturday-quill", memberId: "m33", checkedIn: true, registeredDaysAgo: 57 },
  { eventSlug: "writing-sprint-saturday-quill", memberId: "m25", checkedIn: true, registeredDaysAgo: 58 },
  { eventSlug: "writing-sprint-saturday-quill", memberId: "m19", checkedIn: true, registeredDaysAgo: 59 },
  { eventSlug: "writing-sprint-saturday-quill", memberId: "m6", checkedIn: true, registeredDaysAgo: 60 },
  { eventSlug: "writing-sprint-saturday-quill", memberId: "m38", checkedIn: true, registeredDaysAgo: 61 },
  { eventSlug: "longform-critique-circle-7-quill", memberId: "m2", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "longform-critique-circle-7-quill", memberId: "m33", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "longform-critique-circle-7-quill", memberId: "m25", checkedIn: false, registeredDaysAgo: 2 },
  { eventSlug: "longform-critique-circle-7-quill", memberId: "m19", checkedIn: false, registeredDaysAgo: 3 },
  { eventSlug: "longform-critique-circle-7-quill", memberId: "m6", checkedIn: false, registeredDaysAgo: 4 },
  { eventSlug: "longform-critique-circle-7-quill", memberId: "m38", checkedIn: false, registeredDaysAgo: 5 },
  { eventSlug: "campus-anthology-launch-quill", memberId: "m2", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "campus-anthology-launch-quill", memberId: "m33", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "campus-anthology-launch-quill", memberId: "m25", checkedIn: false, registeredDaysAgo: 2 },
  { eventSlug: "campus-anthology-launch-quill", memberId: "m19", checkedIn: false, registeredDaysAgo: 3 },
  { eventSlug: "campus-anthology-launch-quill", memberId: "m6", checkedIn: false, registeredDaysAgo: 4 },
  { eventSlug: "campus-anthology-launch-quill", memberId: "m38", checkedIn: false, registeredDaysAgo: 5 },
  { eventSlug: "blitz-ladder-round-4-arena", memberId: "m3", checkedIn: true, registeredDaysAgo: 34 },
  { eventSlug: "blitz-ladder-round-4-arena", memberId: "m31", checkedIn: true, registeredDaysAgo: 35 },
  { eventSlug: "blitz-ladder-round-4-arena", memberId: "m23", checkedIn: true, registeredDaysAgo: 36 },
  { eventSlug: "blitz-ladder-round-4-arena", memberId: "m5", checkedIn: true, registeredDaysAgo: 37 },
  { eventSlug: "blitz-ladder-round-4-arena", memberId: "m34", checkedIn: true, registeredDaysAgo: 38 },
  { eventSlug: "blitz-ladder-round-4-arena", memberId: "m26", checkedIn: true, registeredDaysAgo: 39 },
  { eventSlug: "team-league-semifinals-arena", memberId: "m3", checkedIn: true, registeredDaysAgo: 21 },
  { eventSlug: "team-league-semifinals-arena", memberId: "m31", checkedIn: true, registeredDaysAgo: 22 },
  { eventSlug: "team-league-semifinals-arena", memberId: "m23", checkedIn: true, registeredDaysAgo: 23 },
  { eventSlug: "team-league-semifinals-arena", memberId: "m5", checkedIn: true, registeredDaysAgo: 24 },
  { eventSlug: "team-league-semifinals-arena", memberId: "m34", checkedIn: true, registeredDaysAgo: 25 },
  { eventSlug: "team-league-semifinals-arena", memberId: "m26", checkedIn: true, registeredDaysAgo: 26 },
  { eventSlug: "bullet-chess-night-arena", memberId: "m3", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "bullet-chess-night-arena", memberId: "m31", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "bullet-chess-night-arena", memberId: "m23", checkedIn: false, registeredDaysAgo: 2 },
  { eventSlug: "bullet-chess-night-arena", memberId: "m5", checkedIn: false, registeredDaysAgo: 3 },
  { eventSlug: "bullet-chess-night-arena", memberId: "m34", checkedIn: false, registeredDaysAgo: 4 },
  { eventSlug: "bullet-chess-night-arena", memberId: "m26", checkedIn: false, registeredDaysAgo: 5 },
  { eventSlug: "rating-ladder-round-5-arena", memberId: "m3", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "rating-ladder-round-5-arena", memberId: "m31", checkedIn: false, registeredDaysAgo: 1 },
  { eventSlug: "rating-ladder-round-5-arena", memberId: "m23", checkedIn: false, registeredDaysAgo: 2 },
  { eventSlug: "rating-ladder-round-5-arena", memberId: "m5", checkedIn: false, registeredDaysAgo: 3 },
  { eventSlug: "rating-ladder-round-5-arena", memberId: "m34", checkedIn: false, registeredDaysAgo: 4 },
  { eventSlug: "rating-ladder-round-5-arena", memberId: "m26", checkedIn: false, registeredDaysAgo: 5 },
];

export interface Announcement {
  id: string;
  title: string;
  body: string;
  clubSlug: string;
  club: string;
  authorId: string;
  daysAgo: number;
  pinned: boolean;
  audience: "All" | "Coordinators" | "Volunteers";
  priority: "Low" | "Med" | "High";
}
export const announcements: Announcement[] = [
  { id: "a1", title: "Fusion Night VI — Sarga Live, this Thursday, 7 PM", body: "Doors open 6:30, six acts, closing jam open to anyone on stage.", clubSlug: "sarga", club: "Sarga Music Circle", authorId: "m3", daysAgo: 1.2, pinned: true, audience: "All", priority: "High" },
  { id: "a2", title: "Registration for Ignite 2026 closes Wednesday", body: "If you're pitching or just attending, lock in your spot before the cutoff.", clubSlug: "e-cell", club: "E-Cell IITM BS", authorId: "m1", daysAgo: 2, pinned: true, audience: "All", priority: "High" },
  { id: "a3", title: "Weekly Cook-Off moved to Discord voice channel #3", body: "Channel #2 is double-booked with another event's stream — join #3 instead.", clubSlug: "codechef", club: "CodeChef IITM BS", authorId: "m1", daysAgo: 0.5, pinned: false, audience: "All", priority: "Med" },
  { id: "a4", title: "Volunteers: mandatory briefing before Hack-a-Sangam", body: "All assigned volunteers must attend Wednesday's briefing to get shift assignments.", clubSlug: "codechef", club: "CodeChef IITM BS", authorId: "m5", daysAgo: 3.4, pinned: false, audience: "Volunteers", priority: "High" },
  { id: "a5", title: "New coordinators onboarding this Friday", body: "Walkthrough of the approval queue and the volunteer task board for new coordinators.", clubSlug: "paradox", club: "Paradox Debate Society", authorId: "m2", daysAgo: 4.1, pinned: false, audience: "Coordinators", priority: "Med" },
  { id: "a6", title: "Portfolio submissions open for Kalakriti showcase", body: "Submit up to three pieces for next month's showcase wall — deadline Sunday.", clubSlug: "kalakriti", club: "Kalakriti Design Guild", authorId: "m4", daysAgo: 2.8, pinned: false, audience: "All", priority: "Med" },
  { id: "a7", title: "Campus Waste Audit rescheduled to Saturday", body: "Weather pushed the audit to Saturday morning — same meeting point at the main gate.", clubSlug: "prakriti", club: "Prakriti Sustainability", authorId: "m4", daysAgo: 5.3, pinned: true, audience: "All", priority: "High" },
  { id: "a8", title: "Founder Circle applications closing soon", body: "This cohort's founder circle applications close end of week — apply in the club channel.", clubSlug: "e-cell", club: "E-Cell IITM BS", authorId: "m1", daysAgo: 6.6, pinned: false, audience: "All", priority: "Med" },
  { id: "a9", title: "Poetry Slam theme announced: Monsoon Verses", body: "This edition's theme is monsoon — five-minute slots, sign up at the door.", clubSlug: "quill", club: "Quill Writers' Circle", authorId: "m2", daysAgo: 8.9, pinned: false, audience: "All", priority: "Low" },
  { id: "a10", title: "Rating Ladder Round 5 pairings out", body: "Pairings for round 5 are posted on the board and in the club channel.", clubSlug: "arena", club: "Arena Chess Club", authorId: "m3", daysAgo: 1.9, pinned: false, audience: "All", priority: "Med" },
  { id: "a11", title: "BP Open Round venue changed to Seminar Hall 3", body: "Original venue got double-booked — same time, new room.", clubSlug: "paradox", club: "Paradox Debate Society", authorId: "m2", daysAgo: 3, pinned: true, audience: "All", priority: "High" },
  { id: "a12", title: "Sarga jam session this weekend, all welcome", body: "Casual open jam, bring an instrument or just your voice. No auditions.", clubSlug: "sarga", club: "Sarga Music Circle", authorId: "m3", daysAgo: 7.5, pinned: false, audience: "All", priority: "Low" },
  { id: "a13", title: "Volunteer sign-ups open for Ignite 2026", body: "Looking for volunteers across registration, sponsor booths, and stage management.", clubSlug: "e-cell", club: "E-Cell IITM BS", authorId: "m1", daysAgo: 4.7, pinned: false, audience: "Volunteers", priority: "Med" },
  { id: "a14", title: "Design Fest collab planning meeting", body: "Planning meeting for the next cross-club showcase — coordinators only.", clubSlug: "kalakriti", club: "Kalakriti Design Guild", authorId: "m4", daysAgo: 9.2, pinned: false, audience: "Coordinators", priority: "Med" },
];

export interface Issue {
  id: string;
  title: string;
  category: "Registration" | "Payment" | "Booking" | "Access" | "Other";
  status: "Open" | "InProgress" | "Resolved";
  raisedById: string;
  assigneeId?: string;
  clubSlug?: string;
  daysAgo: number;
  priority: "Low" | "Med" | "High";
}
export const issues: Issue[] = [
  { id: "i1", title: "Can't check in for Weekly Cook-Off", category: "Registration", status: "Open", raisedById: "m19", clubSlug: "codechef", daysAgo: 2.1, priority: "High" },
  { id: "i2", title: "Payment for merchandise not reflecting", category: "Payment", status: "InProgress", raisedById: "m20", assigneeId: "m2", clubSlug: "sarga", daysAgo: 5.6, priority: "Med" },
  { id: "i3", title: "Unable to book Seminar Hall for practice session", category: "Booking", status: "Open", raisedById: "m21", clubSlug: "paradox", daysAgo: 8.2, priority: "Med" },
  { id: "i4", title: "Lost access to club Discord after role change", category: "Access", status: "Resolved", raisedById: "m22", assigneeId: "m4", clubSlug: "codechef", daysAgo: 14.9, priority: "High" },
  { id: "i5", title: "Wrong event time shown on my dashboard", category: "Registration", status: "Open", raisedById: "m23", clubSlug: "kalakriti", daysAgo: 1.4, priority: "Low" },
  { id: "i6", title: "Refund request for cancelled workshop", category: "Payment", status: "InProgress", raisedById: "m24", assigneeId: "m6", clubSlug: "kalakriti", daysAgo: 6.8, priority: "Med" },
  { id: "i7", title: "Can't upload avatar image", category: "Access", status: "Resolved", raisedById: "m25", clubSlug: "prakriti", daysAgo: 20.3, priority: "Low" },
  { id: "i8", title: "Duplicate registration for BP Open Round", category: "Registration", status: "Resolved", raisedById: "m26", clubSlug: "paradox", daysAgo: 30.1, priority: "Low" },
  { id: "i9", title: "Task assignment notification not received", category: "Other", status: "Open", raisedById: "m27", clubSlug: "e-cell", daysAgo: 3.7, priority: "Med" },
  { id: "i10", title: "Requesting change of assigned volunteer role", category: "Other", status: "InProgress", raisedById: "m28", assigneeId: "m10", clubSlug: "prakriti", daysAgo: 9.5, priority: "Low" },
  { id: "i11", title: "Event capacity showing incorrect count", category: "Booking", status: "Open", raisedById: "m29", clubSlug: "e-cell", daysAgo: 4.4, priority: "High" },
  { id: "i12", title: "Announcement email not delivered", category: "Other", status: "Resolved", raisedById: "m30", assigneeId: "m2", clubSlug: "sarga", daysAgo: 12.6, priority: "Med" },
  { id: "i13", title: "Unable to withdraw from club", category: "Access", status: "Open", raisedById: "m31", clubSlug: "quill", daysAgo: 18, priority: "Low" },
  { id: "i14", title: "Certificate not generated after event", category: "Other", status: "InProgress", raisedById: "m32", assigneeId: "m4", clubSlug: "arena", daysAgo: 7.1, priority: "Med" },
  { id: "i15", title: "Incorrect attendance marked for me", category: "Registration", status: "Open", raisedById: "m33", clubSlug: "codechef", daysAgo: 2.9, priority: "High" },
];

export interface Task {
  id: string;
  title: string;
  eventSlug: string;
  role: string;
  status: "todo" | "doing" | "done";
  priority: "Low" | "Med" | "High";
  assigneeId: string;
  dueInDays: number;
}
export const tasks: Task[] = [
  { id: "t1", title: "Registration desk setup", eventSlug: "hack-a-sangam-24h-codechef", role: "Logistics", status: "done", priority: "Med", assigneeId: "m11", dueInDays: -15 },
  { id: "t2", title: "Sponsor booth coordination", eventSlug: "ignite-2026-startup-weekend-e-cell", role: "Coordination", status: "doing", priority: "High", assigneeId: "m12", dueInDays: 3 },
  { id: "t3", title: "Sound check and mic setup", eventSlug: "fusion-night-vi-sarga-live-sarga", role: "Tech ops", status: "todo", priority: "Med", assigneeId: "m13", dueInDays: 3 },
  { id: "t4", title: "Judge briefing document", eventSlug: "hack-a-sangam-24h-codechef", role: "Coordination", status: "done", priority: "Med", assigneeId: "m14", dueInDays: -13 },
  { id: "t5", title: "Volunteer T-shirt distribution", eventSlug: "startup-weekend-e-cell", role: "Logistics", status: "done", priority: "Low", assigneeId: "m15", dueInDays: -49 },
  { id: "t6", title: "Stage decoration", eventSlug: "fusion-night-vi-sarga-live-sarga", role: "Hospitality", status: "doing", priority: "Low", assigneeId: "m16", dueInDays: 3 },
  { id: "t7", title: "Waste segregation stations setup", eventSlug: "campus-waste-audit-drive-prakriti", role: "Logistics", status: "done", priority: "Med", assigneeId: "m17", dueInDays: -25 },
  { id: "t8", title: "Photography coverage", eventSlug: "design-fest-prakriti-x-kalakriti-collab-showcase-kalakriti", role: "Content", status: "done", priority: "Low", assigneeId: "m18", dueInDays: -45 },
  { id: "t9", title: "Security desk coordination", eventSlug: "bp-open-round-paradox", role: "Logistics", status: "todo", priority: "Med", assigneeId: "m11", dueInDays: -2 },
  { id: "t10", title: "Certificate printing", eventSlug: "dsa-bootcamp-trees-graphs-codechef", role: "Logistics", status: "todo", priority: "Low", assigneeId: "m12", dueInDays: -1 },
  { id: "t11", title: "Livestream setup", eventSlug: "weekly-cook-off-48-codechef", role: "Tech ops", status: "todo", priority: "Med", assigneeId: "m13", dueInDays: 1 },
  { id: "t12", title: "Feedback form collection", eventSlug: "founder-circle-fundraising-101-e-cell", role: "Content", status: "done", priority: "Low", assigneeId: "m14", dueInDays: -28 },
  { id: "t13", title: "Green room coordination", eventSlug: "fusion-night-vi-sarga-live-sarga", role: "Coordination", status: "todo", priority: "Low", assigneeId: "m15", dueInDays: 4 },
  { id: "t14", title: "Seating arrangement", eventSlug: "poetry-slam-monsoon-verses-quill", role: "Logistics", status: "done", priority: "Low", assigneeId: "m16", dueInDays: -71 },
  { id: "t15", title: "Chess board setup", eventSlug: "blitz-ladder-round-4-arena", role: "Logistics", status: "done", priority: "Med", assigneeId: "m17", dueInDays: -34 },
  { id: "t16", title: "Registration desk", eventSlug: "ignite-2026-startup-weekend-e-cell", role: "Logistics", status: "todo", priority: "Med", assigneeId: "m18", dueInDays: 5 },
  { id: "t17", title: "Banner printing coordination", eventSlug: "illustration-sprint-campus-stories-kalakriti", role: "Content", status: "todo", priority: "Low", assigneeId: "m11", dueInDays: -4 },
  { id: "t18", title: "Motion cards printing", eventSlug: "bp-open-round-ii-paradox", role: "Logistics", status: "todo", priority: "Low", assigneeId: "m12", dueInDays: 12 },
  { id: "t19", title: "Merch table setup", eventSlug: "weekly-cook-off-48-codechef", role: "Logistics", status: "doing", priority: "Low", assigneeId: "m13", dueInDays: 2 },
  { id: "t20", title: "Judge coordination", eventSlug: "rating-ladder-round-5-arena", role: "Coordination", status: "todo", priority: "Med", assigneeId: "m14", dueInDays: 16 },
  { id: "t21", title: "Pitch deck printing", eventSlug: "founder-ama-series-a-lessons-e-cell", role: "Content", status: "todo", priority: "Low", assigneeId: "m15", dueInDays: 22 },
  { id: "t22", title: "Open mic sign-up sheet", eventSlug: "longform-critique-circle-7-quill", role: "Coordination", status: "todo", priority: "Low", assigneeId: "m16", dueInDays: 30 },
  { id: "t23", title: "Tree sapling procurement", eventSlug: "tree-plantation-weekend-prakriti", role: "Logistics", status: "doing", priority: "Med", assigneeId: "m17", dueInDays: 6 },
  { id: "t24", title: "Portfolio wall labels", eventSlug: "illustration-sprint-campus-stories-kalakriti", role: "Content", status: "done", priority: "Low", assigneeId: "m18", dueInDays: -1 },
  { id: "t25", title: "Sustainability Fair volunteer roster", eventSlug: "sustainability-fair-prakriti", role: "Coordination", status: "todo", priority: "Med", assigneeId: "m11", dueInDays: 18 },
];

export interface Contribution {
  id: string;
  eventSlug: string;
  role: string;
  hoursLogged: number;
  verifiedDaysAgo: number;
  memberId: string;
}
export const contributions: Contribution[] = [
  { id: "v1", eventSlug: "hack-a-sangam-24h-codechef", role: "Logistics", hoursLogged: 10, verifiedDaysAgo: -14, memberId: "m11" },
  { id: "v2", eventSlug: "hack-a-sangam-24h-codechef", role: "Coordination", hoursLogged: 7, verifiedDaysAgo: -12, memberId: "m14" },
  { id: "v3", eventSlug: "startup-weekend-e-cell", role: "Logistics", hoursLogged: 4, verifiedDaysAgo: -48, memberId: "m15" },
  { id: "v4", eventSlug: "campus-waste-audit-drive-prakriti", role: "Logistics", hoursLogged: 11, verifiedDaysAgo: -24, memberId: "m17" },
  { id: "v5", eventSlug: "design-fest-prakriti-x-kalakriti-collab-showcase-kalakriti", role: "Content", hoursLogged: 8, verifiedDaysAgo: -44, memberId: "m18" },
  { id: "v6", eventSlug: "founder-circle-fundraising-101-e-cell", role: "Content", hoursLogged: 5, verifiedDaysAgo: -27, memberId: "m14" },
  { id: "v7", eventSlug: "poetry-slam-monsoon-verses-quill", role: "Logistics", hoursLogged: 12, verifiedDaysAgo: -70, memberId: "m16" },
  { id: "v8", eventSlug: "blitz-ladder-round-4-arena", role: "Logistics", hoursLogged: 9, verifiedDaysAgo: -33, memberId: "m17" },
  { id: "v9", eventSlug: "illustration-sprint-campus-stories-kalakriti", role: "Content", hoursLogged: 6, verifiedDaysAgo: 0, memberId: "m18" },
];

export interface ClubMembership {
  clubSlug: string;
  role: "Member" | "Volunteer" | "Coordinator" | "Admin";
  status: "Active" | "Pending" | "Inactive";
  joinedDaysAgo: number;
}
export interface Member {
  id: string;
  name: string;
  roll: string;
  avatar: string;
  interests: string[];
  memberships: ClubMembership[];
}
export const members: Member[] = [
  { id: "m1", name: "Aditya Raghunathan", roll: "22s3001842", avatar: "122", interests: ["Tech","Entrepreneurship","Debate"], memberships: [{ clubSlug: "codechef", role: "Admin", status: "Active", joinedDaysAgo: 640 }, { clubSlug: "e-cell", role: "Admin", status: "Active", joinedDaysAgo: 632 }] },
  { id: "m2", name: "Sneha Bhattacharya", roll: "23s2004417", avatar: "5", interests: ["Debate","Public Speaking","Tech"], memberships: [{ clubSlug: "paradox", role: "Admin", status: "Active", joinedDaysAgo: 640 }, { clubSlug: "quill", role: "Admin", status: "Active", joinedDaysAgo: 632 }] },
  { id: "m3", name: "Karthik Subramaniam", roll: "21s1002556", avatar: "260", interests: ["Music","Dance","Tech"], memberships: [{ clubSlug: "sarga", role: "Admin", status: "Active", joinedDaysAgo: 640 }, { clubSlug: "arena", role: "Admin", status: "Active", joinedDaysAgo: 632 }] },
  { id: "m4", name: "Priyanka Deshmukh", roll: "23s3007729", avatar: "85", interests: ["Design","Photography","Finance"], memberships: [{ clubSlug: "kalakriti", role: "Admin", status: "Active", joinedDaysAgo: 640 }, { clubSlug: "prakriti", role: "Admin", status: "Active", joinedDaysAgo: 632 }] },
  { id: "m5", name: "Rahul Mehta", roll: "23s2001183", avatar: "122", interests: ["Tech","Strategy Games","Sustainability"], memberships: [{ clubSlug: "codechef", role: "Coordinator", status: "Active", joinedDaysAgo: 480 }, { clubSlug: "arena", role: "Member", status: "Active", joinedDaysAgo: 210 }] },
  { id: "m6", name: "Ishita Rao", roll: "22s3005561", avatar: "5", interests: ["Debate","Public Speaking","Design"], memberships: [{ clubSlug: "paradox", role: "Coordinator", status: "Active", joinedDaysAgo: 480 }, { clubSlug: "quill", role: "Member", status: "Active", joinedDaysAgo: 210 }] },
  { id: "m7", name: "Aman Tripathi", roll: "24s1000392", avatar: "45", interests: ["Entrepreneurship","Finance","Writing"], memberships: [{ clubSlug: "e-cell", role: "Coordinator", status: "Active", joinedDaysAgo: 480 }, { clubSlug: "codechef", role: "Member", status: "Active", joinedDaysAgo: 210 }] },
  { id: "m8", name: "Priya Venkataraman", roll: "23s3002270", avatar: "260", interests: ["Music","Dance","Tech"], memberships: [{ clubSlug: "sarga", role: "Coordinator", status: "Active", joinedDaysAgo: 480 }, { clubSlug: "kalakriti", role: "Member", status: "Active", joinedDaysAgo: 210 }] },
  { id: "m9", name: "Kabir Anand", roll: "22s2006648", avatar: "85", interests: ["Design","Photography","Sustainability"], memberships: [{ clubSlug: "kalakriti", role: "Coordinator", status: "Active", joinedDaysAgo: 480 }, { clubSlug: "sarga", role: "Member", status: "Active", joinedDaysAgo: 210 }] },
  { id: "m10", name: "Meera Iyengar", roll: "23s1004415", avatar: "155", interests: ["Sustainability","Entrepreneurship","Public Speaking"], memberships: [{ clubSlug: "prakriti", role: "Coordinator", status: "Active", joinedDaysAgo: 480 }, { clubSlug: "e-cell", role: "Member", status: "Active", joinedDaysAgo: 210 }] },
  { id: "m11", name: "Rohan Kulkarni", roll: "24s2001127", avatar: "122", interests: ["Tech","Debate","Photography"], memberships: [{ clubSlug: "codechef", role: "Volunteer", status: "Active", joinedDaysAgo: 300 }, { clubSlug: "paradox", role: "Member", status: "Active", joinedDaysAgo: 140 }] },
  { id: "m12", name: "Ananya Krishnan", roll: "23s3006654", avatar: "45", interests: ["Entrepreneurship","Finance","Photography"], memberships: [{ clubSlug: "e-cell", role: "Volunteer", status: "Active", joinedDaysAgo: 300 }, { clubSlug: "codechef", role: "Member", status: "Active", joinedDaysAgo: 140 }] },
  { id: "m13", name: "Vivek Choudhary", roll: "22s1003381", avatar: "260", interests: ["Music","Dance","Photography"], memberships: [{ clubSlug: "sarga", role: "Volunteer", status: "Active", joinedDaysAgo: 300 }, { clubSlug: "codechef", role: "Member", status: "Active", joinedDaysAgo: 140 }] },
  { id: "m14", name: "Divya Ramaswamy", roll: "23s2007792", avatar: "122", interests: ["Tech","Entrepreneurship","Dance"], memberships: [{ clubSlug: "codechef", role: "Volunteer", status: "Active", joinedDaysAgo: 300 }, { clubSlug: "e-cell", role: "Member", status: "Active", joinedDaysAgo: 140 }] },
  { id: "m15", name: "Arjun Malhotra", roll: "24s3000915", avatar: "45", interests: ["Entrepreneurship","Finance","Public Speaking"], memberships: [{ clubSlug: "e-cell", role: "Volunteer", status: "Active", joinedDaysAgo: 300 }, { clubSlug: "sarga", role: "Member", status: "Active", joinedDaysAgo: 140 }] },
  { id: "m16", name: "Nisha Pillai", roll: "22s2004470", avatar: "260", interests: ["Music","Dance","Writing"], memberships: [{ clubSlug: "sarga", role: "Volunteer", status: "Active", joinedDaysAgo: 300 }, { clubSlug: "quill", role: "Member", status: "Active", joinedDaysAgo: 140 }] },
  { id: "m17", name: "Siddharth Bose", roll: "23s1006238", avatar: "155", interests: ["Sustainability","Strategy Games","Photography"], memberships: [{ clubSlug: "prakriti", role: "Volunteer", status: "Active", joinedDaysAgo: 300 }, { clubSlug: "arena", role: "Member", status: "Active", joinedDaysAgo: 140 }] },
  { id: "m18", name: "Tanvi Agarwal", roll: "24s2002561", avatar: "85", interests: ["Design","Photography","Strategy Games"], memberships: [{ clubSlug: "kalakriti", role: "Volunteer", status: "Active", joinedDaysAgo: 300 }, { clubSlug: "e-cell", role: "Member", status: "Active", joinedDaysAgo: 140 }] },
  { id: "m19", name: "Harshita Nambiar", roll: "23s3009914", avatar: "122", interests: ["Tech","Design","Finance"], memberships: [{ clubSlug: "codechef", role: "Member", status: "Active", joinedDaysAgo: 260 }, { clubSlug: "kalakriti", role: "Member", status: "Active", joinedDaysAgo: 150 }, { clubSlug: "e-cell", role: "Member", status: "Active", joinedDaysAgo: 90 }, { clubSlug: "quill", role: "Member", status: "Active", joinedDaysAgo: 45 }] },
  { id: "m20", name: "Yash Pandey", roll: "22s1007733", avatar: "5", interests: ["Debate","Public Speaking","Entrepreneurship"], memberships: [{ clubSlug: "paradox", role: "Member", status: "Active", joinedDaysAgo: 257 }, { clubSlug: "prakriti", role: "Member", status: "Active", joinedDaysAgo: 148 }] },
  { id: "m21", name: "Riya Sengupta", roll: "24s2003348", avatar: "260", interests: ["Music","Dance","Strategy Games"], memberships: [{ clubSlug: "sarga", role: "Member", status: "Active", joinedDaysAgo: 254 }, { clubSlug: "e-cell", role: "Member", status: "Active", joinedDaysAgo: 146 }, { clubSlug: "arena", role: "Member", status: "Active", joinedDaysAgo: 88 }] },
  { id: "m22", name: "Naveen Reddy", roll: "23s2008821", avatar: "85", interests: ["Design","Photography","Writing"], memberships: [{ clubSlug: "kalakriti", role: "Member", status: "Active", joinedDaysAgo: 251 }, { clubSlug: "quill", role: "Member", status: "Active", joinedDaysAgo: 144 }] },
  { id: "m23", name: "Pooja Shetty", roll: "22s3002216", avatar: "155", interests: ["Sustainability","Strategy Games","Writing"], memberships: [{ clubSlug: "prakriti", role: "Member", status: "Active", joinedDaysAgo: 248 }, { clubSlug: "arena", role: "Member", status: "Active", joinedDaysAgo: 142 }, { clubSlug: "paradox", role: "Member", status: "Active", joinedDaysAgo: 86 }] },
  { id: "m24", name: "Aryan Khanna", roll: "24s1001570", avatar: "45", interests: ["Entrepreneurship","Finance","Writing"], memberships: [{ clubSlug: "e-cell", role: "Member", status: "Active", joinedDaysAgo: 245 }, { clubSlug: "codechef", role: "Member", status: "Active", joinedDaysAgo: 140 }, { clubSlug: "kalakriti", role: "Member", status: "Active", joinedDaysAgo: 45 }] },
  { id: "m25", name: "Lakshmi Narasimhan", roll: "23s3005589", avatar: "320", interests: ["Writing","Debate","Tech"], memberships: [{ clubSlug: "quill", role: "Member", status: "Active", joinedDaysAgo: 242 }, { clubSlug: "paradox", role: "Member", status: "Active", joinedDaysAgo: 138 }, { clubSlug: "kalakriti", role: "Member", status: "Active", joinedDaysAgo: 84 }] },
  { id: "m26", name: "Dev Patel", roll: "22s2009984", avatar: "0", interests: ["Strategy Games","Music","Tech"], memberships: [{ clubSlug: "arena", role: "Member", status: "Active", joinedDaysAgo: 239 }, { clubSlug: "sarga", role: "Member", status: "Active", joinedDaysAgo: 136 }, { clubSlug: "e-cell", role: "Member", status: "Pending", joinedDaysAgo: 5 }] },
  { id: "m27", name: "Sanjana Menon", roll: "24s3001143", avatar: "122", interests: ["Tech","Design","Public Speaking"], memberships: [{ clubSlug: "codechef", role: "Member", status: "Active", joinedDaysAgo: 236 }, { clubSlug: "kalakriti", role: "Member", status: "Active", joinedDaysAgo: 134 }, { clubSlug: "e-cell", role: "Member", status: "Pending", joinedDaysAgo: 5 }] },
  { id: "m28", name: "Abhishek Bansal", roll: "23s1002867", avatar: "5", interests: ["Debate","Public Speaking","Dance"], memberships: [{ clubSlug: "paradox", role: "Member", status: "Active", joinedDaysAgo: 233 }, { clubSlug: "prakriti", role: "Member", status: "Active", joinedDaysAgo: 132 }] },
  { id: "m29", name: "Kavya Balakrishnan", roll: "22s1005612", avatar: "260", interests: ["Music","Dance","Tech"], memberships: [{ clubSlug: "sarga", role: "Member", status: "Active", joinedDaysAgo: 230 }, { clubSlug: "e-cell", role: "Member", status: "Active", joinedDaysAgo: 130 }, { clubSlug: "arena", role: "Member", status: "Active", joinedDaysAgo: 80 }, { clubSlug: "codechef", role: "Member", status: "Active", joinedDaysAgo: 45 }] },
  { id: "m30", name: "Rajat Kapoor", roll: "24s2004709", avatar: "85", interests: ["Design","Photography","Writing"], memberships: [{ clubSlug: "kalakriti", role: "Member", status: "Active", joinedDaysAgo: 227 }, { clubSlug: "quill", role: "Member", status: "Active", joinedDaysAgo: 128 }] },
  { id: "m31", name: "Nandini Joshi", roll: "23s3003356", avatar: "155", interests: ["Sustainability","Strategy Games","Public Speaking"], memberships: [{ clubSlug: "prakriti", role: "Member", status: "Active", joinedDaysAgo: 224 }, { clubSlug: "arena", role: "Member", status: "Active", joinedDaysAgo: 126 }, { clubSlug: "paradox", role: "Member", status: "Active", joinedDaysAgo: 78 }] },
  { id: "m32", name: "Varun Sethi", roll: "22s2001098", avatar: "45", interests: ["Entrepreneurship","Finance","Sustainability"], memberships: [{ clubSlug: "e-cell", role: "Member", status: "Active", joinedDaysAgo: 221 }, { clubSlug: "codechef", role: "Member", status: "Active", joinedDaysAgo: 124 }] },
  { id: "m33", name: "Ishaan Verma", roll: "24s1006475", avatar: "320", interests: ["Writing","Debate","Strategy Games"], memberships: [{ clubSlug: "quill", role: "Member", status: "Active", joinedDaysAgo: 218 }, { clubSlug: "paradox", role: "Member", status: "Active", joinedDaysAgo: 122 }, { clubSlug: "kalakriti", role: "Member", status: "Active", joinedDaysAgo: 76 }] },
  { id: "m34", name: "Aditi Chatterjee", roll: "23s2002739", avatar: "0", interests: ["Strategy Games","Music","Finance"], memberships: [{ clubSlug: "arena", role: "Member", status: "Active", joinedDaysAgo: 215 }, { clubSlug: "sarga", role: "Member", status: "Active", joinedDaysAgo: 120 }, { clubSlug: "e-cell", role: "Member", status: "Active", joinedDaysAgo: 45 }] },
  { id: "m35", name: "Manish Goyal", roll: "22s3008861", avatar: "122", interests: ["Tech","Design","Strategy Games"], memberships: [{ clubSlug: "codechef", role: "Member", status: "Active", joinedDaysAgo: 212 }, { clubSlug: "kalakriti", role: "Member", status: "Active", joinedDaysAgo: 118 }, { clubSlug: "e-cell", role: "Member", status: "Active", joinedDaysAgo: 74 }] },
  { id: "m36", name: "Swati Kulshreshtha", roll: "24s3005923", avatar: "5", interests: ["Debate","Public Speaking","Tech"], memberships: [{ clubSlug: "paradox", role: "Member", status: "Active", joinedDaysAgo: 209 }, { clubSlug: "prakriti", role: "Member", status: "Active", joinedDaysAgo: 116 }] },
  { id: "m37", name: "Nikhil Bhargava", roll: "23s1009182", avatar: "260", interests: ["Music","Dance","Photography"], memberships: [{ clubSlug: "sarga", role: "Member", status: "Active", joinedDaysAgo: 206 }, { clubSlug: "e-cell", role: "Member", status: "Active", joinedDaysAgo: 114 }, { clubSlug: "arena", role: "Member", status: "Active", joinedDaysAgo: 72 }] },
  { id: "m38", name: "Ritika Saxena", roll: "22s2007345", avatar: "85", interests: ["Design","Photography","Strategy Games"], memberships: [{ clubSlug: "kalakriti", role: "Member", status: "Active", joinedDaysAgo: 203 }, { clubSlug: "quill", role: "Member", status: "Active", joinedDaysAgo: 112 }] },
];

export interface FacultyMember {
  id: string;
  name: string;
  email: string;
}
export const faculty: FacultyMember[] = [
  { id: "f1", name: "Dr. Rajeshwari Nair", email: "rajeshwari.nair@ds.study.iitm.ac.in" },
  { id: "f2", name: "Dr. Vikram Chandrasekhar", email: "vikram.chandrasekhar@ds.study.iitm.ac.in" },
];

export const faqs = [
  { q: "How do I join a club?", a: "Head to Browse Clubs, pick one, hit Join. Some clubs auto-approve; others need admin approval and you'll get a status update." },
  { q: "What if two events I want clash?", a: "Sangam flags conflicts on your dashboard. You can count yourself in for both - attendance is checked in separately - but organizers see who's double-booked." },
  { q: "How does event approval work?", a: "Small events go live instantly. Anything requiring venue booking, funds, or off-campus travel routes to the faculty coordinator queue." },
  { q: "Can I be a member of multiple clubs?", a: "Yes. Most students are in 2–3. Your dashboard filters announcements to only clubs you belong to." },
  { q: "Where do bulk imports live?", a: "Admin → Members → Import CSV. Template is downloadable. Duplicate roll numbers are skipped, not overwritten." },
  { q: "I found a bug. What do I do?", a: "Raise an issue from your dashboard. High-priority tickets ping the platform admin directly." },
];

export const resources = [
  { id: "r1", name: "Amphitheatre", type: "Venue", capacity: 300, availability: "Booked Fri 7 PM" },
  { id: "r2", name: "Seminar Hall 1", type: "Venue", capacity: 80, availability: "Available" },
  { id: "r3", name: "Seminar Hall 2", type: "Venue", capacity: 70, availability: "Available" },
  { id: "r4", name: "Seminar Hall 3", type: "Venue", capacity: 60, availability: "Available" },
  { id: "r5", name: "CRC Auditorium", type: "Venue", capacity: 320, availability: "Pending confirmation" },
  { id: "r6", name: "OAT", type: "Venue", capacity: 150, availability: "Available" },
  { id: "r7", name: "Common Room", type: "Venue", capacity: 80, availability: "Available" },
  { id: "r8", name: "Projector - Epson 4K", type: "Equipment", capacity: 1, availability: "Available" },
  { id: "r9", name: "PA System - Yamaha", type: "Equipment", capacity: 1, availability: "Booked Sat" },
  { id: "r10", name: "DSLR Kit - Canon", type: "Equipment", capacity: 2, availability: "Pending confirmation" },
];

export const metrics = {
  totalMembers: 45,
  activeMembers: 42,
  eventsThisMonth: 25,
  openIssues: 11,
  weeklyAttendance: [21, 19, 14, 12, 16, 10, 199],
  clubGrowth: [
    { club: "CodeChef", growth: 23 },
    { club: "Paradox", growth: 4 },
    { club: "Sarga", growth: 12 },
    { club: "Kalakriti", growth: 3 },
    { club: "Prakriti", growth: 4 },
    { club: "E-Cell", growth: 16 },
    { club: "Quill", growth: -2 },
    { club: "Arena", growth: 6 },
  ],
};

export interface TransparencyEntry {
  id: string;
  eventSlug: string;
  eventName: string;
  outcome: string;
  daysAgo: number;
  clubSlug: string;
  spend: string;
  attendance: string;
}
export const transparencyLog: TransparencyEntry[] = [
  { id: "l1", eventSlug: "hack-a-sangam-24h-codechef", eventName: "Hack-a-Sangam 24h · CodeChef IITM BS", outcome: "Strong turnout, 12 teams shipped working prototypes.", daysAgo: 14, clubSlug: "codechef", spend: "₹18,500", attendance: "90" },
  { id: "l2", eventSlug: "inter-iit-mun-selection-trials-paradox", eventName: "Inter-IIT MUN Selection Trials · Paradox Debate Society", outcome: "Selected 6-member MUN delegation.", daysAgo: 18, clubSlug: "paradox", spend: "₹6,000", attendance: "40" },
  { id: "l3", eventSlug: "semester-showcase-ragas-rhythms-sarga", eventName: "Semester Showcase: Ragas & Rhythms · Sarga Music Circle", outcome: "Sold-out showcase, 14 performances.", daysAgo: 60, clubSlug: "sarga", spend: "₹42,000", attendance: "300" },
  { id: "l4", eventSlug: "design-fest-prakriti-x-kalakriti-collab-showcase-kalakriti", eventName: "Design Fest: Prakriti x Kalakriti Collab Showcase · Kalakriti Design Guild", outcome: "Cross-club collab exhibit, strong footfall.", daysAgo: 45, clubSlug: "kalakriti", spend: "₹12,000", attendance: "150" },
  { id: "l5", eventSlug: "startup-weekend-e-cell", eventName: "Startup Weekend · E-Cell IITM BS", outcome: "18 teams pitched, 3 selected for incubation.", daysAgo: 50, clubSlug: "e-cell", spend: "₹65,000", attendance: "210" },
  { id: "l6", eventSlug: "team-league-semifinals-arena", eventName: "Team League: Semifinals · Arena Chess Club", outcome: "Close semifinal, decided on tiebreak.", daysAgo: 20, clubSlug: "arena", spend: "₹0", attendance: "28" },
];
